# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fdefef2ecd67264d6ed798c4c62512cb50b88cb7abb51d58323ae846390825a759e36203267d9add90985b5ecb0cd91010db01f0d6a4098cf7afea960b95b573

test:
  secret_key_base: 4c66b5395c21eddce8891f8c2c4648c17eb691e6cf81f9ccc550d20a6fc486d8e4bf048c740f4a7cc2dc44976cff4afe52bf000ded3d483908b4aed9041468ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
